apiVersion: v1
kind: Service
metadata:
    name: "tafridaydemok8s-910f"
    labels:
        app: "tafridaydemok8s-910f"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "tafridaydemok8s-910f"